### ISSUE TITLE
bug: no space before closing the brackets

### ISSUE THREAD

**Issue by periclescesar** [wikimedia/grunt-stylelint#47]
Bugging if less is in line and no space before closing the brackets
less:
`.publicacoes-oficiais ul {.borda-preta}`

```
Warning: Running stylelint failed
TypeError: Cannot read property '2' of undefined
  at LessParser.rule (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:64:38)
  at LessParser.createRule (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:110:18)
  at LessParser.ruleWithoutBody (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:141:18)
  at LessParser.processEndOfRule (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:173:22)
  at LessParser.word (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:272:44)
  at LessParser.loop (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:300:30)
  at lessParse (/home/pericles/www/zbox/node_modules/stylelint/node_modules/postcss-less/dist/less-parse.js:23:12)
  at new LazyResult (/home/pericles/www/zbox/node_modules/postcss/lib/lazy-result.js:70:24)
  at Processor.process (/home/pericles/www/zbox/node_modules/postcss/lib/processor.js:117:12)
  at getCode.then.code (/home/pericles/www/zbox/node_modules/stylelint/lib/getPostcssResult.js:83:29)
 Use --force to continue.
```

**Comment by ntwb** [comment]
This might be related to a less bug in stylelint, less hasn't had many contributors of late, would you be interested in taking a look at some issues and seeing if you could help out @periclescesar ?

`postcss-less` has just had a new version released and a new maintainer of the project and any extra eyes on any of this would be fantastic

Some issues and links that might be of some help:
https://github.com/stylelint/stylelint/search?q=less&state=open&type=Issues&utf8=%E2%9C%93
https://github.com/stylelint/stylelint/pull/2547 update `postcss-less` to version `0.16.0`
https://github.com/shellscape/postcss-less

**Comment by Volker-E** [comment]
Tested with v0.9.0 and stylelint 9.1.1 without issues. Closing as there hasn't been any new information in last 6+ month. Feel free to reopen with additional information.
